[package]
product_name = "File Reader"
version = "0.1.0"
description = "This app searches for a file in your whole PC in mere milliseconds"
authors = ["IRISHYURA Yedidiah"]

[[bin]]
name = "seachfile"
main = true

[nsis]
installer_mode = "both" 
